FROM golang:1.14-alpine3.12 as builder
# Must run in parent folder

ARG SOURCE_COMMIT=impexport
ARG SOURCE_TAG=0.0.0
ARG COMMIT_MSG=""
ARG BUILD_VERSION=0.0.0
ARG BUILD_TIME=MISSING
ARG BRANCH=missing

ENV TIME_ZONE=Asia/Taipei
ENV GO111MODULE=on

RUN apk --no-cache add curl git tzdata bash curl-dev zlib-dev libssh2-dev libressl-dev alpine-sdk libgit2-dev && \
    cp /usr/share/zoneinfo/$TIME_ZONE /etc/localtime && \
    echo $TIME_ZONE > /etc/timezone && \
    apk del tzdata

ENV SRC_HOME /go/src/ntc
WORKDIR $SRC_HOME

COPY ./elzion/cicd ./elzion/cicd
COPY ./mclib ./mclib

WORKDIR $SRC_HOME/elzion/cicd

RUN go mod download
COPY ./elzion/cicd/git2go_fix/git_dynamic.go /go/pkg/mod/github.com/libgit2/git2go@v0.28.4/git_dynamic.go

WORKDIR $SRC_HOME/elzion/cicd

RUN export BUILD_TIME=`date '+%F_%H:%M:%S'` && \
    export BUILD_FLAGS="-s -X main.version=$BUILD_VERSION -X main.sourceTag=$SOURCE_TAG -X main.gitHash=$SOURCE_COMMIT -X main.branch='$BRANCH' -X main.buildStamp=$BUILD_TIME" && \
    go build -ldflags "$BUILD_FLAGS" -o cicd

FROM alpine:3.12

ENV SOURCE_COMMIT=$SOURCE_COMMIT
ENV COMMIT_MSG=$COMMIT_MSG
ENV SOURCE_TAG=$SOURCE_TAG
ENV BUILD_VERSION=$BUILD_VERSION
ENV BRANCH=$BRANCH
ENV SMTP_PASSWORD="..."
ENV BUILD_TIME=$BUILD_TIME
ENV TIME_ZONE=Asia/Taipei
ENV BUILDER_SRC_HOME /go/src/ntc
ENV API_PORT 9110

RUN apk --no-cache add tzdata ca-certificates && \
    cp /usr/share/zoneinfo/$TIME_ZONE /etc/localtime && \
    echo $TIME_ZONE > /etc/timezone && \
    rm -rf /var/cache/apk/*

COPY --from=builder /usr/lib/lib* /usr/lib/
WORKDIR /app

COPY --from=builder $BUILDER_SRC_HOME/elzion/cicd/cicd ./

EXPOSE $API_PORT

CMD ["/app/cicd"]
